import type { Product } from "@/../../shared/types";

// Lista de produtos com base no catálogo e nas opções do usuário
// OPÇÃO 1 - Mais Vendidos: Kit Presente Natal Malbec, Her Code Eau De Parfum, Malbec Desodorante Colônia, Kit Presente Natal Lily Soleil, Kit Presente Natal Liz
export const INITIAL_PRODUCTS: Omit<Product, "id" | "createdAt">[] = [
  // MAIS VENDIDOS (Top 5 - Opção 1)
  {
    code: "86172",
    name: "Kit Presente Natal Malbec (4 Itens)",
    description: "Kit com desodorante colônia, loção hidratante mate, body spray e sabonete em barra. Economia de R$ 52,70.",
    price: 269.90,
    originalPrice: 322.60,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B86172/951c4797-8107-49e1-bb75-0550107cb2de-bot-86172-malbec-kit-natal-01.jpg",
    isBestSeller: true,
  },
  {
    code: "50022",
    name: "Her Code Eau De Parfum 50ml",
    description: "Fragrância feminina marcante e sensual. Para mulheres que escrevem suas próprias regras.",
    price: 239.90,
    originalPrice: 239.90,
    volume: "50 ml",
    category: "Perfumes Femininos",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B50022/e96941b2-24cc-4117-ba35-42b12a2d919a-bot-50022-her-code-perfume-edp-perfume-frontal-01.jpg",
    isBestSeller: true,
  },
  {
    code: "84387",
    name: "Malbec Desodorante Colônia 100ml",
    description: "O primeiro desodorante colônia do mundo a ser feito com álcool vínico, envelhecido em barris de carvalho.",
    price: 209.90,
    originalPrice: 209.90,
    volume: "100 ml",
    category: "Perfumes Masculinos",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B84387/3fcf35bd-e85f-416e-bbbb-755c89f39e95-bot-84387-malbec-malbec-desodorante-colonia-frontal-01.jpg",
    isBestSeller: true,
  },
  {
    code: "86181",
    name: "Kit Presente Natal Lily Soleil (2 Itens)",
    description: "Kit com desodorante colônia e creme acetinado para mãos. Economia de R$ 47,90.",
    price: 209.90,
    originalPrice: 257.80,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B86181/c975b10f-8ec9-42b1-a7e9-bd8215aa7735-bot-86181-lily-soilei-kit-natal-01.jpg",
    isBestSeller: true,
  },
  {
    code: "86189",
    name: "Kit Presente Natal Liz (2 Itens)",
    description: "Kit com desodorante colônia e creme desodorante hidratante corporal. Economia de R$ 44,90.",
    price: 169.90,
    originalPrice: 214.80,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B86189/f16dc892-de15-464d-84c0-5a72d9a0bd33-bot-86189-liz-kit-natal-01.jpg",
    isBestSeller: true,
  },

  // PRODUTOS RESTANTES (Baseado no pasted_content.txt e catálogo)
  {
    code: "86170",
    name: "Kit Presente Natal Zaad (3 Itens)",
    description: "Kit com Eau de parfum, espuma para barbear e balm pós-barba. Economia de R$ 62,80.",
    price: 369.90,
    originalPrice: 432.70,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B86170/5b6044d9-51c3-4c88-8880-6f85e590b4bf-bot-86170-zaad-kit-natal-01.jpg",
  },
  {
    code: "Z79360",
    name: "O.U.I Kit Madeleine: EDP 75ml + Crème 200g + Creme Mãos 30g",
    description: "Kit exclusivo O.U.I com Eau de Parfum, Crème corporal e Creme para Mãos. Luxo e sofisticação.",
    price: 499.00,
    originalPrice: 499.00,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/Z79360/8aaaa1a6-da92-40f1-b220-4f9bcec40cdd-oui-79360-kit-natal-madeleiene-862-1.jpg",
  },
  {
    code: "86175",
    name: "Kit Presente Natal Her Code Touch (2 Itens)",
    description: "Kit com Eau de parfum e óleo de massagem corporal. Economia de R$ 59,90.",
    price: 269.90,
    originalPrice: 329.80,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B86175/d915a939-4a1c-413c-a29e-74acdbd248e9-bot-86175-her-code-kit-natal-01.jpg",
  },
  {
    code: "88921",
    name: "Kit Presente Natal Uomini (3 Itens)",
    description: "Kit com desodorante colônia, body spray e nécessaire premium. Economia de R$ 77,80.",
    price: 229.90,
    originalPrice: 307.70,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B88921/bce1d7f0-23a2-4357-8c0b-b8ebafad87d7-bot-88921-uomini-kit-natal-01.jpg",
  },
  {
    code: "58373",
    name: "Floratta Red Blossom Desodorante Colônia 75ml",
    description: "Fragrância floral frutal vibrante. Uma nova versão do Floratta Red.",
    price: 159.90,
    originalPrice: 159.90,
    volume: "75 ml",
    category: "Perfumes Femininos",
    vegan: false,
    image: "https://sgi.e-boticario.com.br/Paginas/Imagens/Produtos/58373GG.jpg",
  },
  {
    code: "82688",
    name: "Egeo Dolce Desodorante Colônia 90ml",
    description: "Fragrância adocicada e divertida. Ideal para quem gosta de perfumes gourmand.",
    price: 154.90,
    originalPrice: 154.90,
    volume: "90 ml",
    category: "Perfumes Femininos",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/products/B82688/Egeo-Des-Col-Dolce-C-Car-90Ml-B82688_.jpg",
  },
  {
    code: "74096",
    name: "Glamour Desodorante Colônia 75ml",
    description: "Fragrância floral amadeirada. Elegância e sofisticação para o dia a dia.",
    price: 149.90,
    originalPrice: 184.90,
    volume: "75 ml",
    category: "Perfumes Femininos",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/products/B74096/GLAMOUR-DES-COL-75ml-V6_B74096_frontal.jpg",
  },
  {
    code: "E94092",
    name: "Club 6 Voyage Desodorante Colônia 95ml",
    description: "Fragrância amadeirada especiada. Para homens que buscam novas experiências.",
    price: 139.90,
    originalPrice: 139.90,
    volume: "95 ml",
    category: "Perfumes Masculinos",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/E94092/c99ee1ec-ac75-49ba-be2a-704b58f165c1-e94092-club-6-voyage-des-col-95ml-frontal.jpg",
  },
  {
    code: "E84671",
    name: "Kit Eudora H (2 Itens)",
    description: "Kit com desodorante colônia e loção pós-barba. Economia de R$ 47,90.",
    price: 111.91,
    originalPrice: 159.89,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/E84671/222ec6cc-c6b8-4f78-adcc-ec0a79666135-e84671-pack-estojo-kit-namorados-eudora-h-1.jpg",
  },
  {
    code: "48060",
    name: "Creme Acetinado Lily 250g",
    description: "Creme acetinado com a fragrância clássica de Lily. Hidratação intensa por 48 horas.",
    price: 139.90,
    originalPrice: 139.90,
    volume: "250 g",
    category: "Hidratantes Corporais",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/products/B48060/LILY-CR-ACET-CPO_V8_B48060_Frontal.jpg",
  },
  {
    code: "48281",
    name: "Loção Nativa Spa Ameixa Negra 400ml",
    description: "Loção desodorante hidratante com a fragrância sensual de Ameixa Negra. Hidratação profunda.",
    price: 86.90,
    originalPrice: 86.90,
    volume: "400 ml",
    category: "Hidratantes Corporais",
    vegan: true,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/products/B48281/NSPA-LOC-DES-HID-CPO-AMEI-NEG-400ml-V3_B48281_.jpg",
  },
  {
    code: "48282",
    name: "Loção Nativa Spa Ameixa 400ml",
    description: "Loção desodorante hidratante com a fragrância clássica de Ameixa. Pele macia e perfumada.",
    price: 86.90,
    originalPrice: 86.90,
    volume: "400 ml",
    category: "Hidratantes Corporais",
    vegan: true,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/products/B48282/Lo%C3%A7%C3%A3o-Hidratante-Desodorante-Corporal-Nativa-SPA-Ameixa.jpg",
  },
  {
    code: "85124",
    name: "Cuide-Se Bem Deleite 400ml",
    description: "Creme hidratante corporal com a fragrância aconchegante de Deleite. Hidratação por 48h.",
    price: 72.90,
    originalPrice: 72.90,
    volume: "400 ml",
    category: "Hidratantes Corporais",
    vegan: true,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B85124/9cb31cfb-9ea5-4c3c-b1b7-b603f8aa0480-bot-85124-cuide-se-bem-de-leite-creme-hidratante-400ml-frontal-01.jpg",
  },
  {
    code: "85542",
    name: "Cuide-Se Bem Deleite Refil 350ml",
    description: "Refil econômico do creme hidratante Deleite. Sustentabilidade e economia.",
    price: 57.90,
    originalPrice: 57.90,
    volume: "350 ml",
    category: "Hidratantes Corporais",
    vegan: true,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/f_auto,fl_progressive,q_auto:best/v1/imagens/product/B85542/ff18fe86-c714-456b-ba4e-19a159a84e53-bot-85542-cuide-se-bem-de-leite-creme-hidratante-refil-01.jpg",
  },
  {
    code: "E86286",
    name: "Kit Instance Baunilha Natal",
    description: "Lembrancinha com miniatura de hidratante e sabonete. Perfeito para presentear.",
    price: 39.90,
    originalPrice: 39.90,
    volume: "Kit Mini",
    category: "Kits Presente",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/E86286/83fcdced-d1c0-4661-ae06-31bc14485e1d-e86286-lembrancinha-instance-baunilha-natal-25-1.jpg",
  },
  // Produtos adicionais do catálogo para completar a loja (com descontos)
  {
    code: "59830",
    name: "Sabonete Líquido Corporal Nativa SPA Orquídea Lumière",
    description: "Sabonete líquido vegano que estimula a produção de colágeno. Economize R$ 12,00.",
    price: 45.90,
    originalPrice: 57.90,
    volume: "250 ml",
    category: "Higiene",
    vegan: true,
    image: "https://images.unsplash.com/photo-1600857062241-98e5dba7214d?w=500&h=600&fit=crop", // Imagem genérica temporária
  },
  {
    code: "85584",
    name: "Óleo Glorioso Desodorante Hidratante Nativa SPA Orquídea Lumière",
    description: "Óleo corporal vegano com fragrância Floral Ambarada. Economize R$ 19,00.",
    price: 73.90,
    originalPrice: 92.90,
    volume: "200 ml",
    category: "Cuidados Corporais",
    vegan: true,
    image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=500&h=600&fit=crop", // Imagem genérica temporária
  },
  {
    code: "86178",
    name: "Presente Coffee Woman Seduction (3 Itens)",
    description: "Kit com desodorante colônia, loção hidratante e sabonete líquido. Economia de R$ 59,80.",
    price: 229.90,
    originalPrice: 289.70,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B86178/d915a939-4a1c-413c-a29e-74acdbd248e9-bot-86178-coffee-woman-seduction-kit-natal-01.jpg", // Imagem genérica temporária
  },
  {
    code: "86173",
    name: "Presente Botica 214 Golden Gardênia (2 Itens)",
    description: "Kit com Eau de parfum e nécessaire feminino dourado. Economia de R$ 55,80.",
    price: 274.90,
    originalPrice: 330.70,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B86173/d915a939-4a1c-413c-a29e-74acdbd248e9-bot-86173-botica-214-golden-gardenia-kit-natal-01.jpg", // Imagem genérica temporária
  },
  {
    code: "86176",
    name: "Presente Floratta Red Passion (2 Itens)",
    description: "Kit com Eau de parfum e creme intenso hidratante corporal. Economia de R$ 30,90.",
    price: 224.90,
    originalPrice: 255.80,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B86176/d915a939-4a1c-413c-a29e-74acdbd248e9-bot-86176-floratta-red-passion-kit-natal-01.jpg", // Imagem genérica temporária
  },
  {
    code: "86192",
    name: "Presente Egeo Choc (3 Itens)",
    description: "Kit com desodorante colônia, suflê hidratante corporal e nécessaire. Economia de R$ 57,80.",
    price: 199.90,
    originalPrice: 257.70,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B86192/d915a939-4a1c-413c-a29e-74acdbd248e9-bot-86192-egeo-choc-kit-natal-01.jpg", // Imagem genérica temporária
  },
  {
    code: "86184",
    name: "Presente Portinari (2 Itens)",
    description: "Kit com desodorante colônia e body spray desodorante. Economia de R$ 47,90.",
    price: 189.90,
    originalPrice: 237.80,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B86184/d915a939-4a1c-413c-a29e-74acdbd248e9-bot-86184-portinari-kit-natal-01.jpg", // Imagem genérica temporária
  },
  {
    code: "86183",
    name: "Presente Floratta Red (3 Itens)",
    description: "Kit com desodorante colônia, loção hidratante corporal e sabonete líquido. Economia de R$ 57,80.",
    price: 189.90,
    originalPrice: 247.70,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B86183/d915a939-4a1c-413c-a29e-74acdbd248e9-bot-86183-floratta-red-kit-natal-01.jpg", // Imagem genérica temporária
  },
  {
    code: "86180",
    name: "Presente Egeo Dolce (2 Itens)",
    description: "Kit com desodorante colônia e merengue mousse hidratante corporal. Economia de R$ 49,90.",
    price: 179.90,
    originalPrice: 229.80,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B86180/d915a939-4a1c-413c-a29e-74acdbd248e9-bot-86180-egeo-dolce-kit-natal-01.jpg", // Imagem genérica temporária
  },
  {
    code: "86179",
    name: "Presente Arbo (2 Itens)",
    description: "Kit com desodorante colônia e body spray desodorante. Economia de R$ 42,90.",
    price: 179.90,
    originalPrice: 222.80,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B86179/d915a939-4a1c-413c-a29e-74acdbd248e9-bot-86179-arbo-kit-natal-01.jpg", // Imagem genérica temporária
  },
  {
    code: "86190",
    name: "Presente Nativa SPA Ameixa Negra (4 Itens)",
    description: "Kit com body splash, loção hidratante corporal e creme para mãos. Economia de R$ 59,80.",
    price: 159.90,
    originalPrice: 219.70,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: true,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B86190/d915a939-4a1c-413c-a29e-74acdbd248e9-bot-86190-nativa-spa-ameixa-negra-kit-natal-01.jpg", // Imagem genérica temporária
  },
  {
    code: "88924",
    name: "Presente Floratta Gold (2 Itens)",
    description: "Kit com desodorante colônia e creme desodorante hidratante corporal. Economia de R$ 42,90.",
    price: 169.90,
    originalPrice: 217.80,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B88924/d915a939-4a1c-413c-a29e-74acdbd248e9-bot-88924-floratta-gold-kit-natal-01.jpg", // Imagem genérica temporária
  },
  {
    code: "86188",
    name: "Presente Quasar Deep Blue (2 Itens)",
    description: "Kit com desodorante colônia e body spray desodorante. Economia de R$ 54,90.",
    price: 174.90,
    originalPrice: 224.80,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B86188/d915a939-4a1c-413c-a29e-74acdbd248e9-bot-86188-quasar-deep-blue-kit-natal-01.jpg", // Imagem genérica temporária
  },
  {
    code: "86191",
    name: "Presente Egeo Blue (2 Itens)",
    description: "Kit com desodorante colônia e shower gel. Economia de R$ 27,90.",
    price: 159.90,
    originalPrice: 187.80,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B86191/d915a939-4a1c-413c-a29e-74acdbd248e9-bot-86191-egeo-blue-kit-natal-01.jpg", // Imagem genérica temporária
  },
  {
    code: "86194",
    name: "Presente Cuide-se Bem Deleite (4 Itens)",
    description: "Kit com body splash, sabonete líquido, loção hidratante e creme para mãos. Economia de R$ 45,70.",
    price: 134.90,
    originalPrice: 180.60,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: true,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B86194/d915a939-4a1c-413c-a29e-74acdbd248e9-bot-86194-cuide-se-bem-deleite-kit-natal-01.jpg", // Imagem genérica temporária
  },
  {
    code: "86193",
    name: "Presente Insensatez (2 Itens)",
    description: "Kit com desodorante colônia e loção hidratante corporal. Economia de R$ 49,90.",
    price: 159.90,
    originalPrice: 209.80,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B86193/d915a939-4a1c-413c-a29e-74acdbd248e9-bot-86193-insensatez-kit-natal-01.jpg", // Imagem genérica temporária
  },
  {
    code: "86200",
    name: "Presente Cuide-se Bem Pessegura (4 Itens)",
    description: "Kit com body splash, creme para mãos, loção hidratante e nécessaire. Economia de R$ 44,70.",
    price: 144.90,
    originalPrice: 189.60,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: true,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B86200/d915a939-4a1c-413c-a29e-74acdbd248e9-bot-86200-cuide-se-bem-pessegura-kit-natal-01.jpg", // Imagem genérica temporária
  },
  {
    code: "86197",
    name: "Presente Nativa SPA Cereja Rouge (2 Itens)",
    description: "Kit com body splash e creme hidratante para mãos. Economia de R$ 42,90.",
    price: 99.90,
    originalPrice: 142.80,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: true,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B86197/d915a939-4a1c-413c-a29e-74acdbd248e9-bot-86197-nativa-spa-cereja-rouge-kit-natal-01.jpg", // Imagem genérica temporária
  },
  {
    code: "86195",
    name: "Presente Celebre Agora Masculino (2 Itens)",
    description: "Kit com desodorante colônia e loção hidratante corporal. Economia de R$ 24,90.",
    price: 119.90,
    originalPrice: 144.80,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B86195/d915a939-4a1c-413c-a29e-74acdbd248e9-bot-86195-celebre-agora-masculino-kit-natal-01.jpg", // Imagem genérica temporária
  },
  {
    code: "86196",
    name: "Presente Celebre Agora Feminino (2 Itens)",
    description: "Kit com desodorante colônia e loção hidratante corporal. Economia de R$ 29,90.",
    price: 119.90,
    originalPrice: 149.80,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B86196/d915a939-4a1c-413c-a29e-74acdbd248e9-bot-86196-celebre-agora-feminino-kit-natal-01.jpg", // Imagem genérica temporária
  },
  {
    code: "88412",
    name: "Presente Cuide-se Bem Splashes (3 Itens)",
    description: "Kit com 3 body splashes (Nuvem, Boa Noite, Morango e Leite). Economia de R$ 29,80.",
    price: 119.90,
    originalPrice: 149.70,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: true,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B88412/d915a939-4a1c-413c-a29e-74acdbd248e9-bot-88412-cuide-se-bem-splashes-kit-natal-01.jpg", // Imagem genérica temporária
  },
  {
    code: "86203",
    name: "Presente Floratta Red (2 Itens)",
    description: "Kit com body spray desodorante e sabonete em barra. Economia de R$ 24,90.",
    price: 59.90,
    originalPrice: 84.80,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B86203/d915a939-4a1c-413c-a29e-74acdbd248e9-bot-86203-floratta-red-kit-natal-01.jpg", // Imagem genérica temporária
  },
  {
    code: "86204",
    name: "Presente Cuide-se Bem Rosa e Algodão (2 Itens)",
    description: "Kit com body splash desodorante colônia e loção hidratante corporal. Economia de R$ 17,90.",
    price: 59.90,
    originalPrice: 77.80,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: true,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B86204/d915a939-4a1c-413c-a29e-74acdbd248e9-bot-86204-cuide-se-bem-rosa-e-algodao-kit-natal-01.jpg", // Imagem genérica temporária
  },
  {
    code: "86201",
    name: "Presente Malbec (2 Itens)",
    description: "Kit com body spray desodorante e sabonete em barra. Economia de R$ 20,90.",
    price: 54.90,
    originalPrice: 75.80,
    volume: "Kit Completo",
    category: "Kits Presente",
    vegan: false,
    image: "https://res.cloudinary.com/beleza-na-web/image/upload/w_500,h_500,f_auto,fl_progressive,q_auto:good/v1/imagens/product/B86201/d915a939-4a1c-413c-a29e-74acdbd248e9-bot-86201-malbec-kit-natal-01.jpg", // Imagem genérica temporária
  },
];

// As categorias presentes são:
// - Kits Presente
// - Perfumes Femininos
// - Perfumes Masculinos
// - Hidratantes Corporais
// - Higiene
// - Cuidados Corporais (será mesclado com Hidratantes Corporais)

// Funções utilitárias para o painel de admin (serão mantidas no useProducts.ts)
// A lista inicial será carregada, mas o painel permitirá a edição e persistência no localStorage.
